train-model:
  image: iterativeai/cml:0-dvc2-base1
  script:
    - pip install -r requirements.txt
    - python new_demo.py
create-cml-report:
  needs: [train-model]
  image: iterativeai/cml:0-dvc2-base1
  script:
    - cat metrics.txt >> report.md
    - cml send-comment report.md
